/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LazyLoadContent {
        "preventRerender": boolean;
    }
}
declare global {
    interface HTMLLazyLoadContentElement extends Components.LazyLoadContent, HTMLStencilElement {
    }
    var HTMLLazyLoadContentElement: {
        prototype: HTMLLazyLoadContentElement;
        new (): HTMLLazyLoadContentElement;
    };
    interface HTMLElementTagNameMap {
        "lazy-load-content": HTMLLazyLoadContentElement;
    }
}
declare namespace LocalJSX {
    interface LazyLoadContent {
        "preventRerender"?: boolean;
    }
    interface IntrinsicElements {
        "lazy-load-content": LazyLoadContent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lazy-load-content": LocalJSX.LazyLoadContent & JSXBase.HTMLAttributes<HTMLLazyLoadContentElement>;
        }
    }
}
